pipeline {
    agent any  
    
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/KonDrozdz/Python-test-app-jenkins.git', 
                     branch: 'main'
            }
        }
        
        stage('Setup') {
            steps {
                
                sh 'python --version'  
                sh 'python -m pip install -r requirements.txt'
            }
        }
        
        stage('Test') {
            steps {
                sh 'python -m pytest tests/ --junitxml=test-results.xml'
            }
            post {
                always {
                    junit 'test-results.xml'  
                }
            }
        }
    }
}
