pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/KonDrozdz/Python-test-app-jenkins.git',
                    branch: 'main'
                )
            }
        }
        
        stage('Test') {
            steps {
                sh 'python -m pytest tests/'
            }
        }
        
        stage('Build Docker') {
            steps {
                sh 'docker build -t python-app .'
            }
        }
    }
    
    post {
        always {
            junit '**/test-results.xml'
        }
    }
}
